@startuml

hide circle
hide empty member

scale max 800 width


title
  |= background color         |= meaning                      |
  |<#red> red                 | belongs to V in MVC pattern   |
  |<#lightgreen> light green  | belongs to C in MVC pattern   |
  |<#yellow> yellow           | belongs to M in MVC pattern   |
  |<#white> white             | value objects                 |
  |<#skyblue> skyblue         | interfaces                    |
end title



  class ServiceForms  #white
  class Views         #white


class Entities  #yellow

class Browsers #red
class Controllers  #lightgreen
class Services     #yellow
class Repositories  #yellow
class DAOs  #yellow
class FeignClients #skyblue



Browsers ..> Controllers : HTTP requests

Controllers ..> Services : call
Services ..> Services : may call
Services ..> FeignClients : may call


Services ..> Repositories : may call
Services ..> DAOs : may call
Entities <- Repositories : retrieve


DAOs -> Entities : retrieve

Entities --o Entities : link to

Controllers ..> Views : use
Controllers ..> ServiceForms : use

Services ..> Views : use
Services ..> ServiceForms : use

FeignClients ..> Views : use
FeignClients ..> ServiceForms : use

ServiceForms --|> Views : may extend

@enduml